### ISSUE TITLE
Raise exception when use Config attribute 

### ISSUE THREAD

**Issue by andrey-mokhov** [spiral/testing#67]
При использовании атрибута `Config` выбрасывается исключение `ConfigDeliveredException`

```php
#[Config('graphql.url', '/url-via-config')]
public function testUrlViaConfig(): void
{
    $config = $this->getContainer()->get(GraphQLConfig::class);
    self::assertSame('/url-via-config', $config->getUrl());
}
```

Дело в том, что бутлоадер моей библиотеки вынужден использовать в методе `boot` экземпляр `GraphQLConfig` и при загрузке приложения конфигурация библиотеки инициализируется, а после уже не [может быть изменена](https://github.com/spiral/framework/blob/master/src/Config/src/ConfigManager.php#L64).

Предлагаю несколько вариантов решения:
1. Позволить управлять [свойством `strict`](https://github.com/spiral/framework/blob/master/src/Config/src/ConfigManager.php#L26) класса `ConfigManager`, т.е. убрать readonly и возможно добавить метод аля `setStrictMode`. Как вариант: контролировать debug режим в этом методе.
2. Продублировать `ConfigurationBootloader` с требуемой функциональностью в неймспейсе `Spiral\Testing` и прописать его в DI-контейнере, но отсюда и очевидный минус - потребуется синхронизировать логику `ConfigurationBootloader`
3. Инициализировать `ConfigManager` [не напрямую](https://github.com/spiral/framework/blob/master/src/Boot/src/Bootloader/ConfigurationBootloader.php#L45), а через DI-контейнер, чтобы была возможность подсунуть свою реализацию. По сути, плюс-минус то же, что и во втором пункте: потребуется последующая синхронизация
4. Каким-либо образом внедриться ещё глубже, например вместо непосредственной инициализации [`DirectoryLoader`](https://github.com/spiral/framework/blob/master/src/Boot/src/Bootloader/ConfigurationBootloader.php#L59) иметь возможность через DI-контейнер подкинуть свою реализацию, которая будет смотреть в том числе на настройки исполняемого тест-кейса (идеи есть как это реализовать) и мержить конфиги из файлов и атрибутов теста.

Вариант под номером 4 на мой взгляд выглядит более перспективным, окружение даже понимать не будет, что данные конфигурации были взяты не из файла, а из тестового окружения.

Если есть другое мнение/идея прошу поделиться.

Готов выполнить доработку и предложить PR, главное определиться каким путем идти.

PS В настоящий момент покрытие тестами [моей библиотеки](https://github.com/andrey-mokhov/graphql-php-spiral) заблокировано отсутствием этой функциональности. Либо придется в библиотеке реализовать 2-й пункт и самостоятельно заморачиватся с синхронизацией.

**Comment by butschster** [comment]
Hi @msmakouz,

What do you think about moving the `strict` property into an ENV variable? You can see its current implementation here: https://github.com/spiral/framework/blob/master/src/Config/src/ConfigManager.php#L26. This change would allow us to disable the strict mode for tests.
