### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by VinterDefoe** [spiral/testing#71]
Feature set up environment variables for test cases not work
![Screenshot from 2024-04-19 00-42-04](https://github.com/spiral/testing/assets/31904991/aed121b5-83bc-4ee3-b83d-71434e7b84bc)

**Comment by butschster** [comment]
Could you show how env variables are used in your application.

**Comment by VinterDefoe** [comment]
Sorry, I was hasty with the mistake. it was changed in EnvironmentInterface
